{
 "title": "CNF monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   },
   { "name": "interval", "query": "4h" }
  ]
 },
 "panels": [
  {
   "title": "Pod Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_phase{namespace=~\"$namespace\",phase=~\"Running\"}) by(namespace, pod, phase)) by(phase)",
     "legendFormat": "{{phase}}"
    },
    {
     "expr": "sum(avg(kube_pod_status_phase{namespace=~\"$namespace\",phase!=\"Running\"} >0) by(namespace, pod, phase)) by(pod,phase)",
     "legendFormat": "{{pod}}_{{phase}}"
    }
   ]
  },
  {
   "title": "Pod Restart",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CNF AllServices Failure",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(sum by(namespace, deployment) (kube_deployment_status_replicas_available{deployment=~\"(amf-comm|amf-ancntl|amf-loc|amf-anintf|nf-idalloc|nf-tmevent|smf-pdusess|smf-pfcpc|sms-pfcpu|upf-pfcpc)\",job=\"kube-state-metrics\",namespace=\"$namespace\"} == 0) or sum by(namespace, statefulset) (kube_statefulset_status_replicas_ready{job=\"kube-state-metrics\",namespace=\"$namespace\",statefulset=~\"(nf-udsfintf|nf-leaderelection|upf-packetprocessing.*)\"} == 0) or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"amf-comm.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"amf-ancntl.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"amf-loc.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"amf-anintf.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"nf-idalloc.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"nf-tmevent.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"smf-pdusess.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"smf-pfcpc.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"smf-pfcpu.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"upf-pfcpc.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"upf-pfcpc.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"nf-leaderelection.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"upf-packetprocessing.*\"}) == 0)",
     "legendFormat": "Alert"
    },
    {
     "expr": "sum by(namespace, deployment) (kube_deployment_status_replicas_available{deployment=~\"(amf-comm|amf-ancntl|amf-loc|amf-anintf|nf-idalloc|nf-tmevent|smf-pdusess|smf-pfcpc|sms-pfcpu|upf-pfcpc)\",job=\"kube-state-metrics\",namespace=\"$namespace\"} == 0) or sum by(namespace, statefulset) (kube_statefulset_status_replicas_ready{job=\"kube-state-metrics\",namespace=\"$namespace\",statefulset=~\"(nf-udsfintf|nf-leaderelection|upf-packetprocessing.*)\"} == 0) or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"amf-comm.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"amf-ancntl.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"amf-loc.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"amf-anintf.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"nf-idalloc.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"nf-tmevent.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"smf-pdusess.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"smf-pfcpc.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"smf-pfcpu.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"upf-pfcpc.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"upf-pfcpc.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"nf-leaderelection.*\"}) == 0 or sum by(namespace) (kube_pod_status_phase{job=\"kube-state-metrics\",namespace=\"$namespace\",phase=~\"Running\",pod=~\"upf-packetprocessing.*\"}) == 0"
    }
   ]
  },
  { "title": "Total Pod and Container Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "POD Count ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Container Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_container_info{namespace=\"$namespace\"}) by (pod) !=0",
     "legendFormat": "{{ pod}}"
    }
   ]
  },
  {
   "title": "CONTAINER Count ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "FD Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(container_file_descriptors\r{namespace=\"$namespace\", container!=\"POD\"}) ",
     "legendFormat": "{{ pod}}"
    }
   ]
  },
  { "title": "CPU Usage & Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum by(namespace) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\"}[2m] ) )",
     "legendFormat": "Current"
    },
    {
     "expr": "sum by(namespace) (kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "Request"
    },
    {
     "expr": "sum by(namespace) (kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\", namespace=\"$namespace\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_user_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\"}[2m] ) )"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum by(pod) (rate(container_cpu_user_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\"}[2m] ) ) / sum(kube_pod_container_resource_requests{resource=\"cpu\",cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\",cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=\"$namespace\"}[2m] ) )/ sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
    }
   ]
  },
  { "title": "Memory Usage & Quota", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\"}[5m])) "
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table-old",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=\"$namespace\",container!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Network Usage",
     "type": "table-old",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[$interval])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[$interval])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[$interval])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[$interval])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[$interval])) by (pod)"
      },
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[$interval])) by (pod)"
      }
     ]
    },
    {
     "title": "Receive Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_bytes_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[$interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Transmit Bandwidth",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[$interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Received Packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[$interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[$interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate of Received Packets Dropped",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_receive_packets_dropped_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[$interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Rate of Transmitted Packets Dropped",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_packets_dropped_total{cluster=\"$cluster\", namespace=~\"$namespace\"}[$interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}