{
 "title": "Kubernetes monitoring by namespace and instance",
 "description": "Monitor a Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Disk usage and number of nodes. As a individual and with the posibility of filter by namespace: POD CPU / Memory / Network usage and PVC usage.",
 "tags": [
  "kubernetes",
  "AKS",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster memory usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{kubernetes_node=~\"$instance\"}) - sum(node_memory_MemFree_bytes{kubernetes_node=~\"$instance\"}+node_memory_Buffers_bytes{kubernetes_node=~\"$instance\"}+node_memory_Cached_bytes{kubernetes_node=~\"$instance\"}) ) / sum(node_memory_MemTotal_bytes{kubernetes_node=~\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (container_name)( rate(container_cpu_usage_seconds_total{image!=\"\", kubernetes_io_hostname=~\"$instance\"}[5m]) )) / count(node_cpu_seconds_total{mode=\"system\", kubernetes_node=~\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "Cluster Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{mountpoint=\"/\",kubernetes_node=~\"$instance\"}) - sum(node_filesystem_free_bytes{mountpoint=\"/\",kubernetes_node=~\"$instance\"}) ) / sum(node_filesystem_size_bytes{mountpoint=\"/\",kubernetes_node=~\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (count by (node)  (kube_node_info))",
     "legendFormat": "#Nodes"
    }
   ]
  },
  {
   "title": "PVC usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 / kubelet_volume_stats_capacity_bytes * kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", instance=~\"$instance\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Pod CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (pod_name)( rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"^$namespace$\",kubernetes_io_hostname=~\"$instance\"}[5m] ) )",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod_name)( rate(container_memory_usage_bytes{image!=\"\",namespace=~\"^$namespace$\",kubernetes_io_hostname=~\"$instance\"}[5m] ) )",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod Network RX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate (container_network_receive_bytes_total{name!=\"\",namespace=~\"^$namespace$\"}[5m])))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Pod Network TX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate (container_network_transmit_bytes_total{name!=\"\",namespace=~\"^$namespace$\",kubernetes_io_hostname=~\"$instance\"}[5m])))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}